[general]
import = ["~/.config/alacritty/themes/themes/duskfox.toml"]
live_config_reload = true

[window]
padding = { x = 4, y = 2 }
opacity = 0.75
blur = true
startup_mode = "Maximized"

[scrolling]
history = 100000
multiplier = 5

[font]
size = 14.0
offset = { x = 0, y = 4 }

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[colors.bright]
black = "0x808080"

[keyboard]
[[keyboard.bindings]]
key   = "D"
mods  = "Alt"
chars = "\u001bd"
[[keyboard.bindings]]
key = "H"
mods = "Alt"
chars = "\u001bh"

[[keyboard.bindings]]
key = "J"
mods = "Alt"
chars = "\u001bj"

[[keyboard.bindings]]
key = "K"
mods = "Alt"
chars = "\u001bk"

[[keyboard.bindings]]
key = "L"
mods = "Alt"
chars = "\u001bl"
